strain_id_field: "genbank_accession"
display_strain_field: "strain"

filter:
  exclude: "config/exclude.txt"
  group_by: "year region"
  min_length:
    genome: 5000
    E: 1000
  sequences_per_group:
    all: '10'
    denv1: '36'
    denv2: '36'
    denv3: '36'
    denv4: '36'

traits:
  sampling_bias_correction: '3'
  traits_columns:
    all: 'region ncbi_serotype nextclade_subtype'
    denv1: 'country region ncbi_serotype nextclade_subtype'
    denv2: 'country region ncbi_serotype nextclade_subtype'
    denv3: 'country region ncbi_serotype nextclade_subtype'
    denv4: 'country region ncbi_serotype nextclade_subtype'

clades:
  clade_definitions:
    all:
      genome: 'config/clades_serotypes.tsv'
      E: 'config/clades_serotypes_E.tsv'
    denv1:
      genome: 'config/clades_genotypes.tsv'
      E: 'config/clades_genotypes_E.tsv'
    denv2:
      genome: 'config/clades_genotypes.tsv'
      E: 'config/clades_genotypes_E.tsv'
    denv3:
      genome: 'config/clades_genotypes.tsv'
      E: 'config/clades_genotypes_E.tsv'
    denv4:
      genome: 'config/clades_genotypes.tsv'
      E: 'config/clades_genotypes_E.tsv'
