# This configuration file should contain all required configuration parameters
# for the ingest workflow to run with additional Nextstrain automation rules.

# Custom rules to run as part of the Nextstrain automated workflow
# The paths should be relative to the ingest directory.
custom_rules:
  - build-configs/nextstrain-automation/upload.smk

# Nextstrain CloudFront domain to ensure that we invalidate CloudFront after the S3 uploads
# This is required as long as we are using the AWS CLI for uploads
cloudfront_domain: "data.nextstrain.org"

# Nextstrain AWS S3 Bucket with pathogen prefix
s3_dst: "s3://nextstrain-data/files/workflows/dengue"

# Mapping of files to upload
files_to_upload:
  genbank.ndjson.xz: data/genbank.ndjson
  all_sequences.ndjson.xz: data/sequences.ndjson
  all/metadata.tsv.zst: results/all/metadata.tsv
  all/sequences.fasta.zst: results/all/sequences.fasta
  denv1/metadata_denv1.tsv.zst: results/denv1/metadata.tsv
  denv1/sequences_denv1.fasta.zst: results/denv1/sequences.fasta
  denv2/metadata_denv2.tsv.zst: results/denv2/metadata.tsv
  denv2/sequences_denv2.fasta.zst: results/denv2/sequences.fasta
  denv3/metadata_denv3.tsv.zst: results/denv3/metadata.tsv
  denv3/sequences_denv3.fasta.zst: results/denv3/sequences.fasta
  denv4/metadata_denv4.tsv.zst: results/denv4/metadata.tsv
  denv4/sequences_denv4.fasta.zst: results/denv4/sequences.fasta
